<?php

namespace WWW\CarsBundle\Repository;

/**
 * ColorCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorCarRepository extends \Doctrine\ORM\EntityRepository
{
}
