<?php

namespace WWW\CarsBundle\Repository;

/**
 * ShareCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareCarRepository extends \Doctrine\ORM\EntityRepository
{
}
