<?php

namespace WWW\CarsBundle\Repository;

/**
 * TypeCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCarRepository extends \Doctrine\ORM\EntityRepository
{
}
