WWW\UserBundle\Entity\Adress:
    type: entity
    table: null
    repositoryClass: WWW\UserBundle\Repository\AdressRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        street:
            type: string
            length: 255
            nullable: true
        name:
            type: string
            length: 255
            nullable: true
        isDefault:
            type: boolean
            nullable: true
        createdDate:
            type: datetime
            nullable: true
        modifiedDate:
            type: datetime
            nullable: true
        deletedDate:
            type: datetime
            nullable: true
        isDeleted:
            type: boolean
            nullable: true
    manyToOne:
        user:
            nullable: true
            targetEntity: User
            inversedBy: Adress
            joinColumn:
                referencedColumnName: id
        cp:
            nullable: true
            targetEntity: ZipCode
            inversedBy: Adress
            joinColumn:
                referencedColumnName: id
    lifecycleCallbacks: {  }
