WWW\UserBundle\Entity\Adress:
    type: entity
    table: null
    repositoryClass: WWW\UserBundle\Repository\AdressRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        street:
            type: string
            length: 255
        name:
            type: string
            length: 255
        isDefault:
            type: boolean
        createdDate:
            type: date
        modifiedDate:
            type: date
        deletedDate:
            type: date
        isDeleted:
            type: boolean
    manyToOne:
        user:
            targetEntity: User
            inversedBy: Adress
            joinColumn:
                referencedColumnName: id
        cp:
            targetEntity: ZipCode
            inversedBy: Adress
            joinColumn:
                referencedColumnName: id
    lifecycleCallbacks: {  }
