WWW\UserBundle\Entity\CodigoPostal:
    type: entity
    table: null
    repositoryClass: WWW\UserBundle\Repository\CodigoPostalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
