WWW\UserBundle\Entity\ConfirmSms:
    type: entity
    table: null
    repositoryClass: WWW\UserBundle\Repository\ConfirmSmsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            length: 255
        date:
            type: datetime
        clicked:
            type: boolean
    manyToOne:
        user:
            targetEntity: User
            inversedBy: ForgottenPassword
            joinColumn:
                referencedColumnName: id
    lifecycleCallbacks: {  }
