WWW\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: WWW\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        surname:
            type: string
            length: 255
            nullable: true
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        sex:
            type: string
            length: '1'
            nullable: true
        birthdate:
            type: date
            nullable: true
        email:
            type: string
            length: 255
            unique: true
        photo:
            type: string
            length: 255
        linkInvitation:
            type: string
            length: 255
            column: link_invitation
        invitNum:
            type: integer
            nullable: true
            column: invit_num
        phone:
            type: integer
        createdDate:
            type: date
        modifiedDate:
            type: date
        deletedDate:
            type: date
        isDeleted:
            type: boolean  
    oneToMany:
        adresses:
            targetEntity: Adress
            mappedBy: User
    lifecycleCallbacks: {  }
