WWW\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: WWW\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        surname:
            type: string
            length: 255
            nullable: true
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
            nullable: true
        sex:
            type: string
            length: '1'
            nullable: true
        birthdate:
            type: date
            nullable: true
        email:
            type: string
            length: 255
            unique: true
        photo:
            type: string
            length: 255
            nullable: true
        linkInvitation:
            type: string
            length: 255
            column: link_invitation
            nullable: true
        invitNum:
            type: integer
            nullable: true
            column: invit_num
            nullable: true
        phone:
            type: integer
            nullable: true
        createdDate:
            type: datetime
            nullable: true
        modifiedDate:
            type: datetime
            nullable: true
        deletedDate:
            type: datetime
            nullable: true
        isDeleted:
            type: boolean
            nullable: true
    oneToMany:
        addresses:
            targetEntity: Address
            mappedBy: User
    lifecycleCallbacks: {  }
