WWW\UserBundle\Entity\Wallet:
    type: entity
    table: null
    repositoryClass: WWW\UserBundle\Repository\WalletRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: float
        date:
            type: datetime
        concept:
            type: string
            length: 255
            nullable: true
        cash:
            type: boolean
        payment:
            type: boolean
        consumed:
            type: boolean
        quantityConsumed:
            type: float
        createdDate:
            type: datetime
            nullable: true
        modifiedDate:
            type: datetime
            nullable: true
        deletedDate:
            type: datetime
            nullable: true
        isDeleted:
            type: boolean
            nullable: true

    manyToOne:
        user:
            targetEntity: User
            inversedBy: wallet
            joinColumn:
                referencedColumnName: id
        service:
            targetEntity: WWW\ServiceBundle\Entity\Service
            joinColumn:
                referencedColumnName: id
    lifecycleCallbacks: {  }
