WWW\UserBundle\Entity\ZipCode:
    type: entity
    table: null
    repositoryClass: WWW\UserBundle\Repository\ZipCodeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        zipCode:
            type: integer
            unique: true
            column: zip_code
        city:
            type: string
            length: 255
        region:
            type: string
            length: 255
        country:
            type: string
            length: 255
        createdDate:
            type: date
        modifiedDate:
            type: date
        deletedDate:
            type: date
        isDeleted:
            type: boolean
    lifecycleCallbacks: {  }
