WWW\UserBundle\Entity\ZipCode:
    type: entity
    table: null
    repositoryClass: WWW\UserBundle\Repository\ZipCodeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        zipCode:
            type: integer
            unique: true
            column: zip_code
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        region:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 255
            nullable: true
        createdDate:
            type: datetime
            nullable: true
        modifiedDate:
            type: datetime
            nullable: true
        deletedDate:
            type: datetime
            nullable: true
        isDeleted:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
