WWW\CarsBundle\Entity\Brand:
    type: entity
    table: null
    repositoryClass: WWW\CarsBundle\Repository\BrandRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
