WWW\ServiceBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: WWW\ServiceBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        comment:
            type: string
            length: 255
            nullable: true
        createdDate:
            type: datetime
            nullable: true
        modifiedDate:
            type: datetime
            nullable: true
        deletedDate:
            type: datetime
            nullable: true
        isDeleted:
            type: boolean
            nullable: true
    manyToOne:
        user:
            targetEntity: WWW\UserBundle\Entity\User
            inversedBy: Comment
            joinColumn:
                referencedColumnName: id
        offer:
            targetEntity: Offer
            inversedBy: Comment
            joinColumn:
                referencedColumnName: id
    lifecycleCallbacks: {  }
