WWW\ServiceBundle\Entity\Concept:
    type: entity
    table: null
    repositoryClass: WWW\ServiceBundle\Repository\ConceptRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reference:
            type: string
            nullable: true
        name:
            type: string
            length: 255
            nullable: true
        description:
            type: string
            length: 255
            nullable: true
        iva:
            type: integer
            nullable: true
        price:
            type: float
            nullable: true
        paid:
            type: boolean
            nullable: true
        payment:
            type: boolean
            nullable: true
    manyToOne:
        billing:
            targetEntity: Billing
            inversedBy: concepts
            joinColumn:
                referencedColumnName: id
        inscription:
            targetEntity: Inscription
            inversedBy: concepts
            joinColumn:
                referencedColumnName: id

    lifecycleCallbacks: {  }
