WWW\ServiceBundle\Entity\Service:
    type: entity
    table: null
    repositoryClass: WWW\ServiceBundle\Repository\ServiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: string
            length: 255
        table:
            type: string
            length: 255
        defaultStatus:
            type: integer
        sellerPenalty:
            type: string
            length: 255
        buyerPenalty:
            type: string
            length: 255
        fatherWallet:
            type: integer
        plusWallet:
            type: integer
    oneToOne:        
        photo:
            targetEntity: WWW\GlobalBundle\Entity\Photo
            joinColumn:
                referencedColumnName: id
    manyToOne:
        category:
            targetEntity: ServiceCategory
            inversedBy: services
            joinColumn:
                referencedColumnName: id
    oneToMany:
        offers:
            targetEntity: Offer
            mappedBy: service
    lifecycleCallbacks: {  }
