<?php

namespace WWW\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CodigoPostalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodigoPostalRepository extends EntityRepository
{
}
