<?php

namespace WWW\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfirmEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfirmEmailRepository extends EntityRepository
{
}
