<?php

namespace WWW\UserBundle\Repository;

/**
 * DownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownRepository extends \Doctrine\ORM\EntityRepository
{
}
