<?php

namespace WWW\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneAttemptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneAttemptRepository extends EntityRepository
{
}
