<?php

namespace WWW\UserBundle\Repository;

/**
 * ServiceJoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceJoinRepository extends \Doctrine\ORM\EntityRepository
{
}
