user_register:
    path: /register/{token}
    defaults: { _controller: UserBundle:Register:register,token:null  }
    
user_login:
    path: /login/
    defaults: { _controller: UserBundle:Login:login }
    
user_logout:
    path: /logout/
    defaults: { _controller: UserBundle:Login:logout }
    
user_profiler:
    path: /profile/
    defaults: { _controller: UserBundle:Profile:profile }
    
user_profiler_editAdress:
    path: /profile/address/{idAddress}/
    defaults: { _controller: UserBundle:ProfileAddress:editAddress }
    requirements:
        idAddress: \d+
    
user_profiler_newAdress:
    path: /profile/newAddress/
    defaults: { _controller: UserBundle:ProfileAddress:newAddress }    
    
user_profiler_offers:
    path: /profile/offer/{idOffer}
    defaults: { _controller: UserBundle:OfferUser:showOffer }
    requirements:
        idOffer: \d+
        
user_profiler_message:
    path: /profile/message/{idMessage}
    defaults: { _controller: UserBundle:Message:searchMessage }
    requirements:
        idMessage: \d+        

user_forgot:
    path: /forgot/
    defaults: { _controller: UserBundle:Default:forgotPass }
    
user_change:
    path: /change/{token}
    defaults: { _controller: UserBundle:Default:changePass }
    
user_resend:
    path: /resend
    defaults: { _controller: UserBundle:Default:resend }
    
user_ajax_message:
    path: /ajax/message
    defaults: { _controller: UserBundle:Message:removeMessage}
    
user_ajax_deleteOffer:
    path: /ajax/deleteOffer
    defaults: { _controller: UserBundle:OfferUser:deleteOffer}  
    
user_ajax_deleteAddress:
    path: /ajax/deleteAddress
    defaults: { _controller: UserBundle:Profile:deleteAddresses}      
