user_register:
    path: /register/
    defaults: { _controller: UserBundle:Register:register }
    
user_login:
    path: /login/
    defaults: { _controller: UserBundle:Login:login }
    
user_logout:
    path: /logout/
    defaults: { _controller: UserBundle:Login:logout }
    
user_profiler:
    path: /profile/
    defaults: { _controller: UserBundle:Profile:profile }
    
user_profiler_offers:
    path: /profile/{offer}/{idOffer}
    defaults: { _controller: UserBundle:OfferUser:showOffer }
    requirements:
        idOffer: \d+

user_forgot:
    path: /forgot/
    defaults: { _controller: UserBundle:Default:forgotPass }
    
user_change:
    path: /change/{token}
    defaults: { _controller: UserBundle:Default:changePass }    