user_register:
    path: /register/{token}
    defaults: { _controller: UserBundle:Register:register,token:null  }

user_login:
    path: /login/
    defaults: { _controller: UserBundle:Login:login }

user_login_check:
    pattern:   /login/
    methods:   [POST]

user_logout:
    path: /logout/
    defaults: { _controller: UserBundle:Login:logout }
    
user_profiler:
    path: /profile/
    defaults: { _controller: UserBundle:Profile:profile }
    
user_profilerPersonal:
    path: /profile/personalData/
    defaults: { _controller: UserBundle:ProfilePersonalData:personalData }
  
user_profilerEmail:
    path: /profile/email/
    defaults: { _controller: UserBundle:ProfileEmail:profileEmail}        
    
user_profilePassword:
    path: /profile/password/
    defaults: { _controller: UserBundle:ProfilePassword:profilePassword}
    
user_profilePhone:
    path: /profile/phone/
    defaults: { _controller: UserBundle:ProfilePhone:profilePhone}

user_profileConfirmPhone:
    path: /profile/phone/confirm/
    defaults: { _controller: UserBundle:ProfilePhone:confirmCode}
    
user_profileChangePhone:
    path: /profile/phone/changePhone/
    defaults: { _controller: UserBundle:ProfilePhone:profileChangePhone}    

user_profilePhoto:
    path: /profile/photo/
    defaults: { _controller: UserBundle:ProfilePhoto:profilePhoto}
    
user_profileChangeBank:
    path: /profile/bank/changeBank/
    defaults: { _controller: UserBundle:ProfileBank:profileBank}
    
user_profileAddress:
    path: /profile/address/
    defaults: { _controller: UserBundle:ProfileAddress:listAddress}
    
user_profiler_editAdress:
    path: /profile/address/{idAddress}/
    defaults: { _controller: UserBundle:ProfileAddress:editAddress }
    requirements:
        idAddress: \d+
    
user_profiler_newAdress:
    path: /profile/newAddress/
    defaults: { _controller: UserBundle:ProfileAddress:newAddress }    
       
user_profiler_offers:
    path: /profile/offers/
    defaults: { _controller: UserBundle:Offer:myOffers }
        
user_profiler_editOffer:    
    path: /profile/offer/{idOffer}/
    defaults: { _controller: UserBundle:Offer:editOffer }
    requirements:
        idOffer: \d+

user_profiler_purchases:
    path: /profile/purchases/
    defaults: { _controller: UserBundle:Purchases:myPurchases }
    
user_profiler_purchasesValoration:
    path: /profile/purchases/valoration/{idOffer}/
    defaults: { _controller: UserBundle:Purchases:valoration }
    requirements:
        idOffer: \d+
        
user_profiler_inscriptions:
    path: /profile/inscription/
    defaults: { _controller: UserBundle:Inscriptions:myInscriptions }
    
user_profileMessage:
    path: /profile/message/
    defaults: { _controller: UserBundle:Message:listMessageReceived}
    
user_profileNewMessage:
    path: /profile/message/new/
    defaults: { _controller: UserBundle:Message:newMessage}
    
user_profileMessageSent:
    path: /profile/message/sent/
    defaults: { _controller: UserBundle:Message:listMessageSent}
    
user_profileMessageReceived:
    path: /profile/message/received/
    defaults: { _controller: UserBundle:Message:listMessageReceived}    
        
user_profiler_readMessage:
    path: /profile/message/{idMessage}/
    defaults: { _controller: UserBundle:Message:searchMessage }
    requirements:
        idMessage: \d+        
       
user_forgot:
    path: /forgot/
    defaults: { _controller: UserBundle:Default:forgotPass }
    
user_change:
    path: /change/{token}/
    defaults: { _controller: UserBundle:Default:changePass }
    
user_resend:
    path: /resend/
    defaults: { _controller: UserBundle:Default:resend }
    
user_ajax_valorationOffer:
    path: /ajax/valorationOffer
    defaults: { _controller: UserBundle:Offer:valorationOffer }
    
user_ajax_deleteMessage:
    path: /ajax/message
    defaults: { _controller: UserBundle:Message:removeMessage }
    
user_ajax_deleteOffer:
    path: /ajax/deleteOffer
    defaults: { _controller: UserBundle:Offer:deleteOffer }
    
user_ajax_deleteImageOffer:
    path: /ajax/deleteImageOffer
    defaults: { _controller: UserBundle:Offer:deleteImageOffer }
    
user_ajax_deleteAddress:
    path: /ajax/deleteAddress
    defaults: { _controller: UserBundle:ProfileAddress:deleteAddresses }    

user_public_profile:
    path: /profile/public/{username}/
    defaults: { _controller: UserBundle:PublicProfile:publicProfile }
    requirements:
            username: \w+

user_unsubscribe:
    path: /profile/unsubscribe/
    defaults: { _controller: UserBundle:ProfileUnsubscribe:unsubscribe }

user_profileNewCar:
    path: /profile/car/new/
    defaults: { _controller: UserBundle:ProfileCar:newCar }

user_profileListCars:
    path: /profile/car/list/
    defaults: { _controller: UserBundle:ProfileCar:listCar }

user_profileCar:
    path: /profile/car/{idCar}/
    defaults: { _controller: UserBundle:ProfileCar:showCar }
    requirements:
            idCar: \d+

user_ajax_deleteCar:
    path: /ajax/deleteCar
    defaults: { _controller: UserBundle:ProfileCar:deleteCar }

user_profileEditCar:
    path: /profile/car/edit/{idCar}/
    defaults: { _controller: UserBundle:ProfileCar:editCar }
    requirements:
        idCar: \d+

user_profileDesignObjects:
    path: /profile/objects/design/
    defaults: { _controller: UserBundle:Default:objects }

user_ajax_deleteImgCar:
    path: /ajax/deleteImgCar/
    defaults: { _controller: UserBundle:ProfileCar:deleteImgCar }

user_validationPhone:
     path: /register/validation/
     defaults: { _controller: UserBundle:Register:validationPhone }

user_resultValidation:
     path: /register/validationConfirmed/{resultConfirm}/
     defaults: { _controller: UserBundle:Register:resultValidation }
     requirements:
        resultConfirm: 1|2

user_ajax_sendSMS:
     path: /ajax/sendSMS
     defaults: { _controller: UserBundle:Register:sendConfirmationCode }

#prueba_validation_false:
#     path: /pruebaValidationFalse
#     defaults: { _controller: UserBundle:Default:pruebaValidationFalse }

user_profile_newHouse:
      path: /profile/house/new/
      defaults: { _controller: UserBundle:ProfileHouse:createHouse }

user_profile_listHouse:
      path: /profile/house/list/
      defaults: { _controller: UserBundle:ProfileHouse:listHouses }

user_profile_editHouse:
      path: /profile/house/edit/{idHouse}/
      defaults: { _controller: UserBundle:ProfileHouse:editHouse }
      requirements:
          idHouse: \d+

user_profile_showHouse:
      path: /profile/house/{idHouse}/
      defaults: { _controller: UserBundle:ProfileHouse:showHouse }
      requirements:
          idHouse: \d+

user_ajax_deleteHouse:
      path: /ajax/deleteHouse/
      defaults: { _controller: UserBundle:ProfileHouse:deleteHouse }

user_ajax_deleteImgHouse:
      path: /ajax/deleteImgHouse/
      defaults: { _controller: UserBundle:ProfileHouse:deleteImgHouse }

