user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_register:
    path: /registro
    defaults: { _controller: UserBundle:Default:showRegister }
    methods: [GET]
    
user_registerUser:
    path: /registro
    defaults: { _controller: UserBundle:Default:register }
    methods: [POST]     