services:
#    www_user.example:
#        class: WWW\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    www_user.profile.form.type:
        class:     WWW\UserBundle\Form\Type\ProfileFormType
        arguments:     [%fos_user.model.user.class%]
        tags:
            - { name:     form.type, alias:     www_user_profile }
            
#    www_user.form.handler.profile:
#        class:     WWW\UserBundle\Form\Handler\ProfileFormHandler
#        arguments:     ["@fos_user.profile.form", "@request", "@fos_user.user_manager", "@fos_user.mailer"]
#        scope:     request
#        public:     false        