WWW\GlobalBundle\Entity\Address:
    type: entity
    table: null
    repositoryClass: WWW\GlobalBundle\Repository\AddressRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        street:
            type: string
            length: 255
            nullable: true
        name:
            type: string
            length: 255
            nullable: true
        zipCode:
            type: string
            length: 255
            column: zip_code
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        region:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 255
            nullable: true  
        createdDate:
            type: datetime
            nullable: true
        modifiedDate:
            type: datetime
            nullable: true
        deletedDate:
            type: datetime
            nullable: true
        isDeleted:
            type: boolean
            nullable: true
    manyToOne:
        user:
            nullable: true
            targetEntity: WWW\UserBundle\Entity\User
            inversedBy: Address
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
