WWW\GlobalBundle\Entity\DateLog:
    type: entity
    table: null
    repositoryClass: WWW\GlobalBundle\Repository\DateLogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateTo:
            type: datetime
            column: date_to
        dateFrom:
            type: datetime
            column: date_from
        price:
            type: integer
            nullable: true
        title:
            type: string
            length: 255
            nullable: true
        occupate:
            type: boolean
            nullable: true
        createdDate:
            type: datetime
            nullable: true
        modifiedDate:
            type: datetime
            nullable: true
        deletedDate:
            type: datetime
            nullable: true
        isDeleted:
            type: boolean
            nullable: true
    manyToOne:
        calendar:
            targetEntity: Calendar
            inversedBy: DateLog
            joinColumn:
                referencedColumnName: id
    lifecycleCallbacks: {  }
