
#acme_redsys:
#    resource:   "@AcmePaymentBundle/Controller/"
#    type:       annotation
#    prefix:     /

prueba_postpago_ok:
    path: /payment/completed
    defaults: { _controller: AcmePaymentBundle:PaymentDoneOK:view }

prueba_postpago_ko:
    path: /payment/failed
    defaults: { _controller: AcmePaymentBundle:PaymentDoneKO:view }

acme_mobile_payment:
    path: /mobile/payments
    defaults: { _controller: AcmePaymentBundle:Mobile:prepare }
 
acme_payment_homepage:
    path:  /payment/offer/{service}/{idOffer}/
#    defaults: { _controller: AcmePaymentBundle:Default:index }
    defaults: { _controller: AcmePaymentBundle:PaymentPurchase:prepare }
    requirements:
        idOffer: \d+
#NO BORRAR ESTOOOO ES EL ROUTIN DEL PAGO CON LA CAIXA        
#acme_payment_card:
#    path: /paymentcard/{service}/offer/{idOffer}/
#    defaults: { _controller: AcmePaymentBundle:PaymentPurchase:card }
#    requirements:
#        idOffer: \d+
#acme_payment_prepare_order_purchase:
#    path:  /payment/prepare_universal/purchase
#    defaults: { _controller: AcmePaymentBundle:PaymentPurchase:prepare }


acme_payment_done:
    path:  /payment/details
    defaults: { _controller: AcmePaymentBundle:Details:view }
    
acme_payment_mobile_done:
    path:  /payment/mobile_details
    defaults: { _controller: AcmePaymentBundle:DetailsMobile:view }
    

    
#acme_payment_notifications_list:
#    path:  /payment/notifications/list
#    defaults: { _controller: AcmePaymentBundle:Notifications:list }
