fullcalendar_loader:
    path: /fc-load-events
    defaults: { _controller: GlobalBundle:Calendar:loadCalendar }
    options:
        expose: true

fullcalendar_edit:
    path: /fc-load-edit
    defaults: { _controller: GlobalBundle:Calendar:editEvent }
    options:
        expose: true
