fullcalendar_loader:
    path: /fc-load-events
    defaults: { _controller: GlobalBundle:Calendar:loadCalendar }
    options:
        expose: true

fullcalendar_delete:
    path: /fc-load-delete
    defaults: { _controller: GlobalBundle:Calendar:deleteEvent }
    options:
        expose: true
