#services:
#    global.example:
#        class: WWW\GlobalBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


services:
    www.globalbundle.calendar_listener:
        class: WWW\GlobalBundle\EventListener\CalendarEventListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }  
       