#OJO en la carpeta admin esta el que se esta usando mejor estructurado
#Dejar este como copia de seguridad

easy_admin:
    disabled_actions: ['delete']
    list:
        actions: ['edit', 'search','show']
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    design:
        brand_color: '#f60'
        menu:
            - label: 'Usuarios'
              children: ['BusquedaUsuario', 'DireccionesUsuarios', 'Message', 'Valoration']
            - label: 'Servicios'
              children: ['Photo','Offer','Inscription','Trade','ShareCar','Car', 'ShareHouse', 'ShareRoom', 'House']
            - label: 'Calendario'
              children: ['MyCompanyEvents', 'Calendar']
            - label: 'Pagos'
              children: ['Payment', 'Billing', 'Concept', 'Wallet']  
            
    site_name: 'Gestión WhatWantWeb'
    entities:
        BusquedaUsuario:
            class: WWW\UserBundle\Entity\User
            label: 'Busqueda de usuarios'
            disabled_actions: ['delete', 'new']
            list:
                title: 'Busqueda de usuarios'
                fields:
                    - id
                    - { property: 'username', label: 'Nick Usuario'}
                    - { property: 'email', label: 'Email', type: 'email'}
                    - { property: 'isConfirmedText', label: 'Confirmado'} #hay que traducir 1 o 0 según proceda
                    - { property: 'phone', label: 'Teléfono'}
                    - photo
                    - defaultAddress
            show:
                title: 'Usuario'
                fields:
                    - { property: 'id', label: 'ID'}
                    - { property: 'username', label: 'Nick Usuario' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'surname', label: 'Apellidos' }
                    - { property: 'sex', label: 'Sexo' }
                    - { property: 'birthdate', label: 'Cumpleaños', type: 'date' }
                    - { property: 'prefix', label: 'Prefijo' }
                    - { property: 'phone', label: 'Teléfono' }
                    - { property: 'isConfirmedText', label: 'Confirmado', type: 'text' }
                    - { property: 'created_date', label: 'Fecha creación cuenta', type: 'datetime'}
                    - { property: 'modified_date', label: 'Fecha último cambio', type: 'datetime'}
                    - { property: 'is_deleted', label: 'Eliminar', type: 'text' }
                    - { property: 'deleted_date', label: 'Fecha eliminado', type: 'datetime'}
#                    - { property: 'offersUser', label: 'Ofertas'}
            form:
                title: 'Usuario'
                fields:
                    - { property: 'id', label: 'ID', type_options: { disabled: true }}
                    - { property: 'username', label: 'Nick Usuario' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'surname', label: 'Apellidos' }
                    - { property: 'sex', label: 'Sexo' }
                    - { property: 'birthdate', label: 'Cumpleaños', type: 'date' }
                    - { property: 'prefix', label: 'Prefijo' }
                    - { property: 'phone', label: 'Teléfono' }
                    - { property: 'is_confirmed', label: 'Confirmado', type: 'text' }
                    - { property: 'created_date', label: 'Fecha creación cuenta', type: 'datetime', type_options: { widget: 'single_text', disabled: true} }
                    - { property: 'modified_date', label: 'Fecha último cambio', type: 'datetime', type_options: { widget: 'single_text', disabled: true} }
                    - { property: 'is_deleted', label: 'Eliminar', type: 'text' }
                    - { property: 'deleted_date', label: 'Fecha eliminado', type: 'datetime', type_options: { widget: 'single_text', disabled: true} }
        DireccionesUsuarios:
            class: WWW\GlobalBundle\Entity\Address
            label: 'Direcciones de usuarios'
            disabled_actions: ['delete', 'new']
            list:
                title: 'Direcciones de usuarios'
                fields:
                    - id
                    - user
                    - { property: 'name', label: 'Nombre', type: 'text' }
                    - { property: 'street', label: 'Dirección', type: 'text' }
                    - { property: 'city', label: 'Ciudad', type: 'text' }
                    - { property: 'region', label: 'Población', type: 'text' }
                    - { property: 'zipCode', label: 'Cod. Postal', type: 'text' }
#                    - { property: 'country', label: 'Pais', type: 'text' }
                    - { property: 'is_deleted', label: 'Borrado', type: 'boolean' }
                    - { property: 'getIsDefaultAddressUser', label: 'Por defecto', type: 'boolean' }
            show:
                title: 'Usuario'
                fields:
                    - id
                    - user
                    - { property: 'name', label: 'Nombre', type: 'text' }
                    - { property: 'street', label: 'Dirección', type: 'text' }
                    - { property: 'city', label: 'Ciudad', type: 'text' }
                    - { property: 'region', label: 'Población', type: 'text' }
                    - { property: 'zipCode', label: 'Cod. Postal', type: 'text' }
                    - { property: 'country', label: 'Pais', type: 'text' }
                    - { property: 'is_deleted', label: 'Borrado' }
                    - { property: 'phoneCompleto', label: 'Teléfono Dirr', type: 'text' }
                    - { property: 'getIsDefaultAddressUser', label: 'Por defecto', type: 'boolean' }



        Message:
            class: WWW\UserBundle\Entity\Message
            label: 'Mensajes'
            list:
#                dql_filter: 'entity.status > 2'
                title: 'Mensajes entre Usuarios'
                fields: #['id','subject','message','status','revisionDate','createdDate','from','to']
                    - id
                    - { property: 'subject', label: 'Titulo', type: 'text'}
                    - { property: 'message', label: 'Mensaje', type: 'text'}
                    - { property: 'statusString', label: 'Estado', type: 'text'}
                    - { property: 'revisionDate', label: 'Fecha Revisión' }
                    - { property: 'createdDate', label: 'Fecha Alta'}
                    - { property: 'fromNick', label: 'Emisor', sortable: true}
                    - { property: 'toNick', label: 'Remitente'}
            form:
                help: 'Introduzca un número según la siguiente leyenda:<br> 0 -> enviado,<br> 1 -> rechazado,<br> 2 -> aprobado,<br> 3 -> leido'
                fields:
                    - status
                    - { property: 'revisionDate',format: 'j/n/Y' }
            new:
                title: 'Mensaje a usuario'
        Photo:
            class: WWW\GlobalBundle\Entity\Photo
            label: 'Fotos'
            list:
                fields:
                    - id
                    - { property: 'url', type: 'image', base_path: 'https://whatwantweb.com/JS9NAJ8JEABj8jcsk9xbGTC7VSM9XAMbaxnbs3873778dhd4m' }
                    - { property: 'createdDate',format: 'j/n/Y'}
                    - { property: 'modifiedDate',format: 'j/n/Y'}
                    - isDeleted
                    
            show:
                fields:
                    - id
                    - { property: 'url', type: 'image', base_path: 'https://whatwantweb.com/JS9NAJ8JEABj8jcsk9xbGTC7VSM9XAMbaxnbs3873778dhd4m' }
                    - { property: 'createdDate',format: 'j/n/Y'}
                    - { property: 'modifiedDate',format: 'j/n/Y'}
                    - isDeleted
        
        Offer:
            class: WWW\ServiceBundle\Entity\Offer
            label: 'Ofertas'
            help: 'Aqui se muestran todas las ofertas en general'
            list:
                fields:
                    - id  
                    - { property: 'serviceId', type: 'text'}
                    - userAdmin
                    - expired
                    - holders
                    - isDeleted
                    - { property: 'createdDate', format: 'j/n/Y'}
                    - { property: 'modifiedDate',format: 'j/n/Y'}
            show:
                title: 'Oferta'
                fields:
                    - id
                    - { property: 'serviceId', type: 'text'}
                    - userAdmin
                    - { property: 'photos', type: 'collection'}
                    - expired
                    - holders
                    - isDeleted
                    - { property: 'createdDate', format: 'j/n/Y'}
                    - { property: 'modifiedDate',format: 'j/n/Y'}
        
        Inscription:
            class: WWW\ServiceBundle\Entity\Inscription
            label: 'Inscripciones'
            help: 'Recuerde los significados de los estados: <br>  0 -> peticion,<br> 1 -> denegado,<br> 2 -> aceptado, <br> 3 -> pagado, <br> 4 -> cancelado, <br>  5 -> consumido'
            list:
                fields:
                    - id 
                    - { property: 'userNick', label: 'Nick del usuario', sortable: true}
                    - offer
                    - { property: 'status',label: 'Estado de la inscripción'}
                    - dataExtra
            show:
                fields:
                    - id 
                    - { property: 'userNick', label: 'Nick del usuario'}
                    - offer
                    - { property: 'status',label: 'Estado de la inscripción'}
                    - dataExtra
            form:
                fields:
                    - id 
                    - { property: 'status',label: 'Estado de la inscripción'}
                    - dataExtra
            
        Concept:
            class: WWW\ServiceBundle\Entity\Concept
            label: 'Conceptos Facturas'    
            
        Billing:
            class: WWW\ServiceBundle\Entity\Billing
            label: 'Facturas'
            
        Payment:
            class: Acme\PaymentBundle\Entity\Payment
            label: 'Pagos'

        MyCompanyEvents:
            class: WWW\GlobalBundle\Entity\MyCompanyEvents
            label: 'Eventos del Calendario'
            
        Calendar: #revisar esta entidad
            class: WWW\GlobalBundle\Entity\Calendar
            label: 'Calendarios'
        
        Valoration:
            class: WWW\ServiceBundle\Entity\Valoration
            label: 'Valoraciones'

        Wallet:
            class: WWW\UserBundle\Entity\Wallet
            label: 'Bolsa'            
        
        Trade:
            class: WWW\OthersBundle\Entity\Trade
            label: 'Ofertas de Compra-Venta' 
            
        ShareCar:
            class: WWW\CarsBundle\Entity\ShareCar
            label: 'Ofertas de Vehículos' 
            
        Car:
            class: WWW\CarsBundle\Entity\Car
            label: 'Coches' 
        
        ShareHouse:
            class: WWW\HouseBundle\Entity\ShareHouse
            label: 'Casa Compartida'
        
        ShareRoom:
            class: WWW\HouseBundle\Entity\ShareRoom
            label: 'Habitación Compartida'
            
        House:
            class: WWW\HouseBundle\Entity\House
            label: 'Casas'