imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@GlobalBundle/Resources/config/services.yml" }
    - { resource: "@ServiceBundle/Resources/config/services.yml" }
    - { resource: "@OthersBundle/Resources/config/services.yml" }
    - { resource: "@CarsBundle/Resources/config/services.yml" }
    - { resource: "@PaymentBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

    assets:  
        packages:
            img: 
                base_urls: 'https://whatwantweb.com/n19n382d23HnNY7bb8nj0m9nyb988676HUUBY6g7J9JI/'

        
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'formTemplate/formBootstrap.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

gregwar_captcha:
    width: 200
    height: 50
    length: 4

payum:
    security:
        token_storage:
            WWW\PaymentBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        WWW\PaymentBundle\Entity\Payment: { doctrine: orm }
        WWW\PaymentBundle\Entity\PaymentDetails: { doctrine: orm }
    gateways:
        offline:
            factory: offline
        paypal_payment:
                     factory: paypal_express_checkout
                     username:  'get this from gateway side'
                     password:  'get this from gateway side'
                     signature: 'get this from gateway side'
                     sandbox: true

easy_admin:
    disabled_actions: ['new']
    list:
        actions: ['edit', 'search','show']
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    design:
        brand_color: '#f60'
    site_name: 'WhatWantWeb_Management'
    entities:
        Message:
            class: WWW\UserBundle\Entity\Message
            list:
                fields: ['id','subject','message','status','revisionDate','createdDate','from','to']
            form:
                fields:
                    - status
                    - { property: 'revisionDate',format: 'j/n/Y' }
        Photo:
            class: WWW\GlobalBundle\Entity\Photo
            list:
                fields:
                    - id
                    - { property: 'url', type: 'image', base_path: 'https://whatwantweb.com/' }
                    - { property: 'createdDate',format: 'j/n/Y'}
                    - { property: 'modifiedDate',format: 'j/n/Y'}
        Trade:
            class: WWW\OthersBundle\Entity\Trade
        Offer:    
            class: WWW\ServiceBundle\Entity\Offer
        User:
            disabled_actions: ['show']
            class: WWW\UserBundle\Entity\User
            list:
                fields: ['id','name','surname','username','email','phone','isBanned']
                    
        Address:
            class: WWW\GlobalBundle\Entity\Address
         
