imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: payum.yml }
    - { resource: admin.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@GlobalBundle/Resources/config/services.yml" }
    - { resource: "@ServiceBundle/Resources/config/services.yml" }
    - { resource: "@OthersBundle/Resources/config/services.yml" }
    - { resource: "@PDFBundle/Resources/config/services.xml" }
    - { resource: "@CarsBundle/Resources/config/services.yml" }
    - { resource: "@HouseBundle/Resources/config/services.yml" }



# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

    assets:  
        packages:
            img: 
                base_urls: 'https://whatwantweb.com/JS9NAJ8JEABj8jcsk9xbGTC7VSM9XAMbaxnbs3873778dhd4m/'

        
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'formTemplate/formBootstrap.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

#doctrine_mongodb:
#  connections:
#    default: # <-- indentation added here
#      server: mongodb://localhost:27017
#      options: {}
#  default_database: test_database
#  document_managers:
#    default:
#      auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

gregwar_captcha:
    width: 200
    height: 50
    length: 4

knp_snappy:
    pdf:
        enabled: true
        binary: C:/wkhtmltopdf/bin/wkhtmltopdf.exe
        options: []

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:

#KnpPaginatorBundle

knp_paginator:
    page_range: 5  # número de páginas a mostrar
    default_options:
          page_name: page # nombre del parámetro de paginación
          sort_field_name: sort # nombre del parámetro para ordenar los registros
          sort_direction_name: direction # nombre del parámetro para ordenar la dirección de los registros
          distinct: true # incluir resultados diferentes, útil en consultas con GROUP BY
    template:
          pagination: ::paginator/custom_pagination.html.twig # plantilla utilizada en la paginación
          sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # plantilla utilizada en la paginación para ordenar los resultados