www_user:
    resource: "@WWWUserBundle/Resources/config/routing.yml"
    prefix:   /

www_home:
    path:     /
    defaults: {_controller: AppBundle:Index:index}
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

www_user_profile:
    path: /profile
    defaults: {_controller: WWWUserBundle:Default:show}

    
