www_user:
    resource: "@WWWUserBundle/Resources/config/routing.yml"
    prefix:   /User

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"