www_user:
    resource: "@WWWUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

www_user_register:
    path: /register
    defaults: {_controller: WWWUserBundle:Default:register}

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

www_user_profile:
    path: /profile
    defaults: {_controller: WWWUserBundle:Default:show}
    methods: [GET]
    
www_user_profile_edit:
    path: /profile
    defaults: {_controller: WWWUserBundle:Default:edit }
    methods: [POST]
