user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_register:
    path: /registro
    defaults: { _controller: UserBundle:Default:showRegister }
    methods: [GET]
    
