others:
    resource: "@OthersBundle/Resources/config/routing.yml"
    prefix:   /

service:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /

global:
    resource: "@GlobalBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_register:
    path: /registro
    defaults: { _controller: UserBundle:Register:register }
    
user_login:
    path: /login
    defaults: { _controller: UserBundle:Login:login }
    
user_logout:
    path: /logout
    defaults: { _controller: UserBundle:Login:logout }
    
user_change:
    path: /change/{token}
    defaults: { _controller: UserBundle:Default:changePass }

user_forgot:
    path: /forgot
    defaults: { _controller: UserBundle:Default:forgotPass }
    
user_profiler:
    path: /perfil
    defaults: { _controller: UserBundle:Profile:profile }

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    
service_trade:
    path: /services/trade
    defaults: { _controller: OthersBundle:Trade:createOfert }
