user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_register:
    path: /registro
    defaults: { _controller: UserBundle:Default:showRegister }
    methods: [GET]
    
user_registerUser:
    path: /registro
    defaults: { _controller: UserBundle:Default:register }
    methods: [POST]    
    
user_login:
    path: /login
    defaults: { _controller: UserBundle:Default:login }
    
user_logout:
    path: /logout
    defaults: { _controller: UserBundle:Default:logout }

    