user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_register:
    path: /registro
    defaults: { _controller: UserBundle:Default:register }
    
user_login:
    path: /login
    defaults: { _controller: UserBundle:Default:login }
    
user_logout:
    path: /logout
    defaults: { _controller: UserBundle:Default:logout }

    
user_profiler:
    path: /perfil
    defaults: { _controller: UserBundle:Default:profile }
user_profiler:
    path: /perfil
    defaults: { _controller: UserBundle:Default:profile }

aboutUs:
    path: /about-us
    defaults: { _controller: AppBundle:Index:aboutUs }
    
siteMap:
    path: /site-map
    defaults: { _controller: AppBundle:Index:siteMap }
    
orders:
    path: /orders
    defaults: { _controller: AppBundle:Index:orders }
    
devolutions:
    path: /devolutions
    defaults: { _controller: AppBundle:Index:devolutions }
    
contact:
    path: /contact
    defaults: { _controller: AppBundle:Index:contact }
    
shipping:
    path: /shipping
    defaults: { _controller: AppBundle:Index:shipping }
    
privacyPolicy:
    path: /privacy-policy
    defaults: { _controller: AppBundle:Index:privacyPolicy }
    
paymentMethod:
    path: /payment-method
    defaults: { _controller: AppBundle:Index:paymentMethod }
