#s_gestion_admin:
#    resource: "@SGestionAdminBundle/Resources/config/routing.yml"
#    prefix:   /
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

aboutUs:
    path: /about-us
    defaults: { _controller: AppBundle:Index:aboutUs }
    
siteMap:
    path: /site-map
    defaults: { _controller: AppBundle:Index:siteMap }
    
orders:
    path: /orders
    defaults: { _controller: AppBundle:Index:orders }
    
devolutions:
    path: /devolutions
    defaults: { _controller: AppBundle:Index:devolutions }
    
contact:
    path: /contact
    defaults: { _controller: AppBundle:Index:contact }
    
shipping:
    path: /shipping
    defaults: { _controller: AppBundle:Index:shipping }
    
privacyPolicy:
    path: /privacy-policy
    defaults: { _controller: AppBundle:Index:privacyPolicy }
    
paymentMethod:
    path: /payment-method
    defaults: { _controller: AppBundle:Index:paymentMethod }
    
serShareCar:
    path: /services/share-car
    defaults: { _controller: AppBundle:Index:serShareCar }
    
serHouseRents:
    path: /services/house-rents
    defaults: { _controller: AppBundle:Index:serHouseRents }
    
offTrade:
    path: /services/trade/offer
    defaults: { _controller: AppBundle:Index:offTrade }   
    
offShareCar:
    path: /services/share-car/offer
    defaults: { _controller: AppBundle:Index:offShareCar }   
    
offHouseRents:
    path: /services/house-rents/offer
    defaults: { _controller: AppBundle:Index:offHouseRents }
    
blog:
    path: /blog
    defaults: { _controller: AppBundle:Index:blog }      
    
admin:
    path: /admin
    defaults: { _controller: AppBundle:Index:admin }  
    
gregwar_captcha_routing:
   resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    
trade:
    resource: "@OthersBundle/Resources/config/routing.yml"
    prefix:   /services/trade  

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
# app/config/routing.yml
adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"    