# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.usr_voter:
            class: AppBundle\Security\UsrVoter
            tags:
                - { name: security.voter }
            arguments: ['@security.access.decision_manager']
            # peque単a mejora de rendimiento
            public: false
            
    app.offer_voter:
            class: AppBundle\Security\OfferVoter
            arguments: ['@security.access.decision_manager']
            tags:
                - { name: security.voter }
            # peque単a mejora de rendimiento
            public: false
    app.msgpriv_voter:
            class: AppBundle\Security\MsgPrivVoter
            arguments: ['@security.access.decision_manager']
            tags:
                - { name: security.voter }
            # peque単a mejora de rendimiento
            public: false
    app.msgoffer_voter:
            class: AppBundle\Security\MsgOfferVoter
            arguments: ['@security.access.decision_manager']
            tags:
                - { name: security.voter }
            # peque単a mejora de rendimiento
            public: false