## YAML Template.
---
easy_admin:
    entities:
        BusquedaUsuario:
            class: WWW\UserBundle\Entity\User
            label: 'Busqueda de usuarios'
            disabled_actions: ['delete', 'new']
            list:
                title: 'Busqueda de usuarios'
                fields:
                    - id
                    - { property: 'username', label: 'Nick Usuario'}
                    - { property: 'email', label: 'Email', type: 'email'}
                    - { property: 'isConfirmedText', label: 'Confirmado'} #hay que traducir 1 o 0 según proceda
                    - { property: 'phone', label: 'Teléfono'}
                    - photo
                    - defaultAddress
            show:
                title: 'Usuario'
                fields:
                    - { property: 'id', label: 'ID'}
                    - { property: 'username', label: 'Nick Usuario' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'surname', label: 'Apellidos' }
                    - { property: 'sex', label: 'Sexo' }
                    - { property: 'birthdate', label: 'Cumpleaños', type: 'date' }
                    - { property: 'prefix', label: 'Prefijo' }
                    - { property: 'phone', label: 'Teléfono' }
                    - { property: 'isConfirmedText', label: 'Confirmado', type: 'text' }
                    - { property: 'created_date', label: 'Fecha creación cuenta', type: 'datetime'}
                    - { property: 'modified_date', label: 'Fecha último cambio', type: 'datetime'}
                    - { property: 'is_deleted', label: 'Eliminar', type: 'text' }
                    - { property: 'deleted_date', label: 'Fecha eliminado', type: 'datetime'}
#                    - { property: 'offersUser', label: 'Ofertas'}
            form:
                title: 'Usuario'
                fields:
                    - { property: 'id', label: 'ID', type_options: { disabled: true }}
                    - { property: 'username', label: 'Nick Usuario' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'name', label: 'Nombre' }
                    - { property: 'surname', label: 'Apellidos' }
                    - { property: 'sex', label: 'Sexo' }
                    - { property: 'birthdate', label: 'Cumpleaños', type: 'date' }
                    - { property: 'prefix', label: 'Prefijo' }
                    - { property: 'phone', label: 'Teléfono' }
                    - { property: 'is_confirmed', label: 'Confirmado', type: 'checkbox' }
                    - { property: 'created_date', label: 'Fecha creación cuenta', type: 'datetime', type_options: { widget: 'single_text', disabled: true} }
                    - { property: 'modified_date', label: 'Fecha último cambio', type: 'datetime', type_options: { widget: 'single_text', disabled: true} }
                    - { property: 'is_deleted', label: 'Eliminar', type: 'checkbox' }
                    - { property: 'deleted_date', label: 'Fecha eliminado', type: 'datetime', type_options: { widget: 'single_text', disabled: true} }