## YAML Template.
---
easy_admin:
    entities:
        Message:
            class: WWW\UserBundle\Entity\Message
            label: 'Mensajes'
            list:
#                dql_filter: 'entity.status > 2'
                title: 'Mensajes entre Usuarios'
                fields: #['id','subject','message','status','revisionDate','createdDate','from','to']
                    - id
                    - { property: 'subject', label: 'Titulo', type: 'text'}
                    - { property: 'message', label: 'Mensaje', type: 'text'}
                    - { property: 'statusString', label: 'Estado', type: 'text'}
                    - { property: 'revisionDate', label: 'Fecha Revisión' }
                    - { property: 'createdDate', label: 'Fecha Alta'}
                    - { property: 'fromNick', label: 'Emisor', sortable: true}
                    - { property: 'toNick', label: 'Remitente'}
            form:
                help: 'Introduzca un número según la siguiente leyenda:<br> 0 -> enviado,<br> 1 -> rechazado,<br> 2 -> aprobado,<br> 3 -> leido'
                fields:
                    - status
                    - { property: 'revisionDate',format: 'j/n/Y' }
            new:
                title: 'Mensaje a usuario'