## YAML Template.
---
easy_admin:
    entities:
        Offer:
            class: WWW\ServiceBundle\Entity\Offer
            label: 'Ofertas'
            list:
                help: 'Aqui se muestran todas las ofertas en general'
                fields:
                    - id  
                    - { property: 'serviceId', type: 'text'}
                    - { property: 'userAdmin', label: 'Usuario'}
                    - { property: 'expired',label: 'Expirada' ,type: 'boolean'}
                    - { property: 'holders',label: 'Capacidad' }
                    - { property: 'isDeleted',label: 'Borrada' ,type: 'boolean'}
                    - { property: 'createdDate', format: 'j/n/Y'}
                    - { property: 'modifiedDate',format: 'j/n/Y'}
            show:
                title: 'Oferta'
                fields:
                    - id  
                    - { property: 'serviceId', type: 'text'}
                    - { property: 'userAdmin', label: 'Usuario'}
                    - { property: 'expired',label: 'Expirada' ,type: 'boolean'}
                    - { property: 'holders',label: 'Capacidad' }
                    - { property: 'isDeleted',label: 'Borrada' ,type: 'boolean'}
                    - { property: 'createdDate', format: 'j/n/Y'}
                    - { property: 'modifiedDate',format: 'j/n/Y'}
            form:
                title: 'Oferta'
                fields:
                    - { property: 'expired',label: 'Expirada' ,type: 'checkbox'}
                    - { property: 'holders',label: 'Capacidad' }
                    - { property: 'isDeleted',label: 'Borrada' ,type: 'checkbox'}
                    