<?php

namespace WWW\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessengerServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessengerServiceRepository extends EntityRepository
{
}
