<?php

namespace WWW\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCategoryRepository extends EntityRepository
{
}
