<?php

namespace WWW\GlobalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MyCompanyEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyCompanyEventsRepository extends EntityRepository
{
}
