<?php

namespace WWW\GlobalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrefixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrefixRepository extends EntityRepository
{
}
