<?php

namespace WWW\OthersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TradeCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeCategoryRepository extends EntityRepository
{
}
