service_newTrade:
    path: /trade/newTrade
    defaults: { _controller: OthersBundle:Trade:createOffer }

service_listTrade:
    path: /trade/
    defaults: { _controller: OthersBundle:Trade:listTrade }
    
service_trade:
    path: /trade/offer/{idOffer}/
    defaults: { _controller: OthersBundle:Trade:showTrade }
    requirements:
        idOffer: \d+

ajax_rating:
    path: /ajax/ajax_rating
    defaults: { _controller: OthersBundle:Trade:prueba }

service_newBarter:
    path: /barter/newBarter/
    defaults: { _controller: OthersBundle:Trade:createOffer }

service_listBarter:
    path: /barter/
    defaults: { _controller: OthersBundle:Trade:listTrade }

service_barter:
    path: /barter/offer/{idOffer}/
    defaults: { _controller: OthersBundle:Trade:showTrade }
    requirements:
        idOffer: \d+

service_newClothes:
    path: /clothes/newClothers/
    defaults: { _controller: OthersBundle:Trade:createOffer }

service_listClothes:
    path: /clothes/
    defaults: { _controller: OthersBundle:Trade:listTrade }

service_clothes:
    path: /clothes/offer/{idOffer}/
    defaults: { _controller: OthersBundle:Trade:showTrade }
    requirements:
        idOffer: \d+

