service_newTrade:
    path: /newTrade
    defaults: { _controller: OthersBundle:Trade:createOffer }

service_listTrade:
    path: /
    defaults: { _controller: OthersBundle:Trade:listTrade }
    
service_trade:
    path: /offer/{idOffer}/
    defaults: { _controller: OthersBundle:Trade:showTrade }
    requirements:
        idOffer: \d+

ajax_rating:
    path: /ajax/ajax_rating
    defaults: { _controller: OthersBundle:Trade:prueba }
        

