#house_homepage:
  #   path:     /
  #  defaults: { _controller: HouseBundle:Default:index }

serHouseRents:
    path: /house-rents/
    defaults: { _controller: HouseBundle:HouseOffers:listOfferShareHouse }

offHouseRents:
    path: /house-rents/offer/{idOffer}
    defaults: { _controller: HouseBundle:HouseOffers:showOfferShareHouse }
    requirements:
          idOffer: \d+

building_newOfferHouseRent:
    path: /house-rents/newOffer/
    defaults: { _controller: HouseBundle:HouseOffers:createNewOffer }


house_lisShareHouse:
    path: /share-house/
    defaults: { _controller: HouseBundle:HouseOffers:listOfferShareHouse}