#house_homepage:
  #   path:     /
  #  defaults: { _controller: HouseBundle:Default:index }

serHouseRents:
    path: /house-rents/
    defaults: { _controller: HouseBundle:HouseOffers:listOfferShareHouse }

offHouseRents:
    path: /house-rents/offer/{idOffer}/
    defaults: { _controller: HouseBundle:HouseOffers:showOfferShareHouse }
    requirements:
          idOffer: \d+

building_newOfferHouseRent:
    path: /house-rents/newOffer/
    defaults: { _controller: HouseBundle:HouseOffers:createNewOffer }

house_lisShareHouse:
    path: /share-house/
    defaults: { _controller: HouseBundle:HouseOffers:listOfferShareHouse }

house_newOfferShareHouse:
    path: /share-house/newOffer/
    defaults: { _controller: HouseBundle:HouseOffers:createNewOffer }

house_offerShareHouse:
    path: /share-house/offer/{idOffer}/
    defaults: { _controller: HouseBundle:HouseOffers:showOfferShareHouse }
    requirements:
            idOffer: \d+

house_listHouseSwap:
    path: /house-swap/
    defaults: { _controller: HouseBundle:HouseOffers:listOfferShareHouse}

house_newOfferHouseSwap:
    path: /house-swap/newOffer/
    defaults: { _controller: HouseBundle:HouseOffers:createNewOffer }

house_offerHouseSwap:
    path: /house-swap/offer/{idOffer}
    defaults: { _controller: HouseBundle:HouseOffers:showOfferShareHouse }
    requirements:
            idOffer: \d+

house_listBedroomSwap:
    path: /bedroom-swap/
    defaults: { _controller: HouseBundle:BedroomOffers:listOfferBedroom }

house_newOfferBedroomSwap:
    path: /bedroom-swap/newOffer/
    defaults: { _controller: HouseBundle:BedroomOffers:createNewOffer }

house_offerBedroomSwap:
    path: /bedroom-swap/offer/{idOffer}
    defaults: { _controller: HouseBundle:BedroomOffers:showOfferBedroom }
    requirements:
            idOffer: \d+

  house_datepicker:
  path: /fc-load-datepicker
  defaults: { _controller: HouseBundle:HouseOffers:form }
 options:
        expose: true