#house_homepage:
  #   path:     /
  #  defaults: { _controller: HouseBundle:Default:index }

serHouseRents:
    path: /house-rents/
    defaults: { _controller: AppBundle:Index:serHouseRents }

offHouseRents:
    path: /house-rents/offer/{idOffer}
    defaults: { _controller: HouseBundle:HouseOffers:listOfferShareHouse }
    requirements:
          idOffer: \d+

building_newOfferHouseRent:
    path: /house-rents/newOffer/
    defaults: { _controller: HouseBundle:HouseOffers:createNewOffer }

