car_shareCarNew:
  path:  /share-car/newOffer/
  defaults: { _controller: CarsBundle:ShareCar:createShareCar }

serShareCar:
  path: /share-car/
  defaults: { _controller: CarsBundle:ShareCar:listCar }

offShareCar:
    path: /share-car/offer/{idOffer}/
    defaults: { _controller: CarsBundle:ShareCar:offerCar }
    requirements:
        idOffer: \d+

shareCar_inscriptions:
  path: /share-car/offer/{idOffer}/inscriptions/
  defaults: { _controller: CarsBundle:ShareCar:inscriptions }
  requirements:
      idOffer: \d+

shareCar_messenger:
    path:  /newOffer/

#serShareCar:
#    path: /services/share-car
#    defaults: { _controller: AppBundle:Index:serShareCar }
