car_shareCarNew:
  path:  /newOffer/
  defaults: { _controller: CarsBundle:ShareCar:createShareCar }

serShareCar:
  path: /
  defaults: { _controller: CarsBundle:ShareCar:listCar }

offShareCar:
    path: /offer/{idOffer}/
    defaults: { _controller: CarsBundle:ShareCar:offerCar }
    requirements:
        idOffer: \d+

shareCar_inscriptions:
  path: /offer/{idOffer}/inscriptions/
  defaults: { _controller: CarsBundle:ShareCar:inscriptions }
  requirements:
      idOffer: \d+


#serShareCar:
#    path: /services/share-car
#    defaults: { _controller: AppBundle:Index:serShareCar }
