<?php

namespace WWW\HouseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShareHouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareHouseRepository extends EntityRepository
{
}
